### PR TITLE
Fix AccessViolationException for DrawLineAA (codeplex 22105)

### PR DESCRIPTION
**Pull request by Plike**
Ran into the same issue as described on http://writeablebitmapex.codeplex.com/workitem/22105

### CODE REVIEW

**Comment by mdenhoedt** [comment]
Seems a good change to me!

**Comment by mdenhoedt** [comment]
I saw that this function doesn't work properly (with `DrawPolylineAa`), because there were gaps between lines. After changing the following line the problem was solved:

    } while(u <= uend);

to:

    } while(u <= uend);

**Comment by Plike** [comment]
I don't see a difference in your suggested change. I think you're talking about replacing 
[WriteableBitmapLineExtensions.cs line 1111](https://github.com/teichgraf/WriteableBitmapEx/blob/master/Source/WriteableBitmapEx/WriteableBitmapLineExtensions.cs#L1111)?

Anyway, you should do a seperate pull request for that I guess :)

**Comment by mdenhoedt** [comment]
Oops, you are right. I changed it. Yeah I will, but I saw not much activity going on here 😞.

**Comment by teichgraf** [comment]
Sorry for the delay and thanks for PR! Merging it now.

**Pull request merged**
