### PR TITLE
Drawing of a dotted line

### PR DESCRIPTION
**Pull request by Chriscolm**
Either I did not understand the purpose of DrawLinePenned or it does not work as I exspected it, so I created a new Method DrawLineDotted, which fits my personal needs and draws a line like this: - - - -

### CODE REVIEW

**Comment by teichgraf** [comment]
Thanks Chris! I added some comments to your pull request.
Note, the DrawLinePenned is used to copy stamp another bitmap using a blit along a line.

**Comment by Chriscolm** [comment]
Moin teichgraf,
I changed Math.Round to Convert.ToInt32, which seems to be twice faster that Math.Round and I also followed your other suggestions, which indeed has a very positive performance impact, thanks for those useful hints!

**Comment by Chriscolm** [comment]
I am quite sure that the compiler inlines the method calls to GetIndex, the same with the property access. 
I chose COnvert.ToInt because it rounds correctly, (int)x.9 will always return x, not x + 1. But I will think about your suggestions after the weekend :-)

**Comment by teichgraf** [comment]
Any updates here?

**Comment by teichgraf** [comment]
Should we still keep this open?

**Comment by Chriscolm** [comment]
I am still drawing dotted lines, I put the code in another class with the approbiate extension method. But I do not know if it is of general interst

**Comment by teichgraf** [comment]
Would be great to get that included if you get a chance to update the PR.

**Comment by Chriscolm** [comment]
> Would be great to get that included if you get a chance to update the PR.

Done

**Comment by teichgraf** [comment]
Thank you so much @Chriscolm 

I merged it in and removed the used file DottedLines.cs Also updated the WPF Shapes sample to use the dotted line for the static grid. Great job.

**Comment by Chriscolm** [comment]
> Thank you so much @Chriscolm
> 
> I merged it in and removed the used file DottedLines.cs Also updated the WPF Shapes sample to use the dotted line for the static grid. Great job.

No prob and thank you :-)

**Pull request merged**
